## YAML Template.
---
#spring:
#  datasource:
#    url: "jdbc:mariadb://192.168.0.10:55408/schoolwebdb"
#    username: "schoolwebuser"
#    password: "abcdef89"
#    ##password: "failtest"
#    driverClassName: "org.mariadb.jdbc.Driver"
server:
  tomcat:
    use-relative-redirects: true
  servlet:
    contextPath: /schoolshorts
  error:
    whitelabel:
      enabled: false
    path: /error
    includeMessage: always
    includeStacktrace: always
    includeException: true